import React, { Fragment } from 'react'
// import Counter from '../components/counter/Counter'
import { Divider } from 'antd'
import Announcement from '../components/announcement'
import BannerList from '../components/banner-list'
import FooterMain from '../components/footer-main'

/* type IBannerList = {
  title: string
  // typeList: 'latest' | 'favorites' | 'filter'
  // modeView: 'tile' | 'list'
} */

/* const bannerListLatest: IBannerList = {
  title: 'Latest Banners',
} */

export const Home: React.FC = () => {
  const titleList: string = 'Latest Banners'
  return (
    <Fragment>
      <div className="mt-1">
        <Announcement />
        <Divider type="horizontal" />
      </div>
      <BannerList titleList={titleList} />
      {/* <h1>Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
      <Counter /> */}
      <div className="mt-1" />
      <FooterMain />
    </Fragment>
  )
}
