export const LOAD_BANNER = 'LOAD_BANNER'
export const LOAD_BANNER_ERROR = 'LOAD_BANNER_ERROR'
export const LOAD_RECENT_BANNERS = 'LOAD_RECENT_BANNERS'
export const LOAD_RECENT_BANNERS_ERROR = 'LOAD_RECENT_BANNERS_ERROR'
